sudo: required
language: generic

services:
  - docker

# Set environment variable COALA_BRANCH=<branch> to override
# the default.
env:
  global:
    - SOURCE_BRANCH=$TRAVIS_BRANCH
    - IMAGE_NAME=coala-docker

install:
  - hooks/build

script:
  - docker images
  - hooks/test

notifications:
  email: false
