sudo: required

services:
  - docker

install:
  - docker build -f Dockerfile -t coala-docker .
  - docker images

script:
  - >
    docker run -t -i coala-docker /bin/sh -c "
      cd /coala; python3 -m pytest --cov --cov-fail-under=100;
      cd /coala-bears;
      rm -rf tests/vhdl tests/verilog/;
      rm tests/c_languages/CSharpLintBearTest.py;
      rm tests/java/InferBearTest.py;
      python3 -m pytest --cov --cov-fail-under=100
    "

notifications:
  email: false
