sudo: required
dist: trusty

cache:
  directories:
    - ~/.zypper-cache

services:
  - docker

install:
  - curl -fsSL https://apt.dockerproject.org/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb https://apt.dockerproject.org/repo/ ubuntu-trusty main"
  - sudo apt-get update
  - sudo apt-get -y install docker-engine
  - docker --version
  - mkdir -p $HOME/.zypper-cache
  - docker build -f Dockerfile -t coala-docker --volume=$HOME/.zypper-cache:/var/cache/zypp:z .
  - docker images

script:
  - >
    docker run -t -i coala-docker /bin/sh -c "
      cd /coala; python3 -m pytest --cov --cov-fail-under=100;
      cd /coala-bears;
      rm bears/Constants.py;  # There are no tests covering this module
      rm bears/c_languages/CSharpLintBear.py tests/c_languages/CSharpLintBearTest.py;
      rm bears/java/InferBear.py tests/java/InferBearTest.py;
      rm bears/haskell/GhcModBear.py tests/haskell/GhcModBearTest.py;
      rm -r bears/verilog tests/verilog/;
      python3 -m pytest --cov --cov-fail-under=100
    "
  - /bin/sh -c "! docker run coala-docker"
  - docker run --user=$(id -u) --volume=$(pwd)/.ci/sample:/work --workdir=/work coala-docker
  - ls -la ./.ci/sample/.coafile
  - echo -e "[fail]\nbears = NoCommentsBear\nfile = **.py" >> ./.ci/sample/.coafile
  - /bin/sh -c "! docker run --user=$(id -u) --volume=$(pwd)/.ci/sample:/work --volume=$(pwd)/.ci/bears:/additional_bears --workdir=/work coala-docker"
notifications:
  email: false
