sudo: required
language: generic

services:
  - docker

# Set environment variable COALA_BRANCH=<branch> to override
# the default.
env:
  global:
    - SOURCE_BRANCH=$TRAVIS_BRANCH
    - IMAGE_NAME=coala-docker

install:
  - hooks/build

script:
  - docker images
  - >
    docker run -t -i --volume=$(pwd)/tests:/work coala-docker /bin/sh -c "
      set -e -x;
      /work/pytest.sh;
      /work/vcs.sh;
    "
  # Verify MarkdownBear works outside of coala-bears directory.
  # See https://github.com/coala/coala-bears/issues/1235
  - >
    docker run -t -i coala-docker /bin/sh -c "
      cd /tmp;
      echo foo > foo.md;
      coala --non-interactive --no-config --bears MarkdownBear --files foo.md;
    "
  - /bin/sh -c "! docker run coala-docker"
  - docker run --volume=$(pwd)/.ci/sample:/work --workdir=/work coala-docker
  - ls -la ./.ci/sample/.coafile
  - sudo chown $USER ./.ci/sample/.coafile
  - echo -e "[fail]\nbears = NoCommentsBear\nfile = **.py" >> ./.ci/sample/.coafile
  - /bin/sh -c "! docker run --volume=$(pwd)/.ci/sample:/work --volume=$(pwd)/.ci/bears:/additional_bears --workdir=/work coala-docker"
notifications:
  email: false
