sudo: required

services:
  - docker

install:
  - docker build -f Dockerfile -t coala-docker .
  - docker images

script:
  - mkdir coala-bears
  - docker create -v ./coala-bears:/coala-bears --name test-container coala-docker
  - docker start test-container
  - docker run test-container -t -i /bin/sh -c "cd /coala; python3 -m pytest --cov; cd /coala-bears; python3 -m pytest"

notifications:
  email: false
