#!/usr/bin/env bash

set -e -x

# This is run on DockerCloud, and not run on Travis

export DEBIAN_FRONTEND=noninteractive
export GOPATH=$HOME/goroot
export PATH=$PATH:/usr/lib/go-1.6/bin/:$GOPATH/bin

time apt-get --yes install golang-1.6-go
time go get github.com/grammarly/rocker
