#!/usr/bin/env bash

set -e -x

docker run -i --volume=$(pwd)/tests:/work $IMAGE_NAME /bin/sh -c "
  set -e -x;
  /work/pytest.sh;
  /work/vcs.sh;
  /work/opensuse.sh;
"

# Verify MarkdownBear works outside of coala-bears directory.
# See https://github.com/coala/coala-bears/issues/1235
docker run -i $IMAGE_NAME /bin/sh -c "
  set -e -x;
  cd /tmp;
  echo foo > foo.md;
  coala --non-interactive --no-config --bears MarkdownBear --files foo.md;
"

# Verify MarkdownBear works outside of coala-bears directory.
# See https://github.com/coala/coala-bears/issues/1235
docker run -i $IMAGE_NAME /bin/sh -c "
  cd /tmp;
  echo foo > foo.md;
  coala --non-interactive --no-config --bears MarkdownBear --files foo.md;
"

! docker run $IMAGE_NAME

docker run --volume=$(pwd)/.ci/sample:/work --workdir=/work $IMAGE_NAME
ls -la ./.ci/sample/.coafile

sudo chown $USER ./.ci/sample/.coafile
echo -e "[fail]\nbears = NoCommentsBear\nfile = **.py" >> ./.ci/sample/.coafile
! docker run --volume=$(pwd)/.ci/sample:/work --volume=$(pwd)/.ci/bears:/additional_bears --workdir=/work $IMAGE_NAME
